name: Code Coverage

on:
  push:
    paths:
      - "**/*.test.ts"
      - "**/__tests__/**/*.ts"
  pull_request:
    paths:
      - "**/*.test.ts"
      - "**/__tests__/**/*.ts"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: |
          npm ci
          npm run test:coverage

      - name: Coveralls Upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
